tap "d12frosted/emacs-plus"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
brew "readline"
brew "sqlite"
brew "xz"
brew "python@3.9"
brew "exa"
brew "ffmpeg"
brew "git"
brew "neovim", args: ["HEAD"]
brew "openssl@3"
brew "pyenv"
brew "ripgrep"
brew "sheldon"
brew "tig"
brew "youtube-dl"
brew "zlib"
brew "d12frosted/emacs-plus/emacs-plus@28", args: ["with-elrumo2-icon", "with-no-titlebar"]
cask "amethyst"
cask "font-fira-code-nerd-font"
cask "kitty"
cask "maccy"
cask "slack"
cask "telegram"
cask "visual-studio-code"
